version: "3.1"

services:
  back:
    build: .
    container_name: django-reservations
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./reservations:/opt/back
    ports:
      - "8000:8000"
