name: Build Docker Image and Run Tests

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILD_CONTEXT: .

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.DOCKER_BUILD_CONTEXT }}
        tags: myimage

    - name: Check if Docker image was built successfully
      run: |
        if [ "$(docker images -q myimage:latest 2> /dev/null)" == "" ]; then
          echo "Docker image build failed!"
          exit 1
        fi
    - name: Run Tests in Container
      run: |
        docker run --name mycontainer -d myimage
        docker exec mycontainer python manage.py test
        TEST_EXIT_CODE=$?
        docker stop mycontainer
        docker rm mycontainer
        if [ $TEST_EXIT_CODE -eq 0 ]; then
          echo "Tests passed!"
        else
          echo "Tests failed!"
          exit 1
        fi
